### ISSUE TITLE
so confused

### ISSUE THREAD

**Issue by Pyyrx0** [kbdevs/ai-aimbot#10]
i have literally no idea what to do with the notes lol, could you please explain with a list step by step for me?

**Comment by kbdevs** [comment]
> i have literally no idea what to do with the notes lol, could you please explain with a list step by step for me?

What do you mean "the notes"?

Do you want like a step by step tutorial for installing/running?

**Comment by Pyyrx0** [comment]
> > i have literally no idea what to do with the notes lol, could you please explain with a list step by step for me?
> 
> 
> 
> What do you mean "the notes"?
> 
> 
> 
> Do you want like a step by step tutorial for installing/running?

Yes I need a step by step for the running of the script and installing the software

**Comment by kbdevs** [comment]
> > > i have literally no idea what to do with the notes lol, could you please explain with a list step by step for me?
> > 
> > 
> > What do you mean "the notes"?
> > Do you want like a step by step tutorial for installing/running?
> 
> Yes I need a step by step for the running of the script and installing the software

Well first you'll need python
https://www.python.org/downloads/
Install it and check the add to path option
Run the script like I did in the bad tutorial
if it says you dont have a module 
pip3 install (name of module)
until it works 

anymore issues past this
https://chat.openai.com
