### ISSUE TITLE
switching to cpu?

### ISSUE THREAD

**Issue by Ugniakas8901** [kbdevs/ai-aimbot#11]
i try to use the 1.3 streamer and the window just doesnt respond and show a gray screen after like a minute it shows [ WARN:0@50.884] global net_impl.cpp:178 cv::dnn::dnn4_v20230620::Net::Impl::setUpNet DNN module was not built with CUDA backend; switching to CPU

**Comment by kbdevs** [comment]
> i try to use the 1.3 streamer and the window just doesnt respond and show a gray screen after like a minute it shows [ WARN:0@50.884] global net_impl.cpp:178 cv::dnn::dnn4_v20230620::Net::Impl::setUpNet DNN module was not built with CUDA backend; switching to CPU

First of all the streamer version doesn't have an overlay so it will never show one, if you want the overlay use the normal version.
If its showing gray on the window you have to go through the options in the terminal.
If you want gpu you must build opencv with the guide at the bottom of the readme.
