### ISSUE TITLE
plz

### ISSUE THREAD

**Issue by charlieiscoollikeu** [kbdevs/ai-aimbot#15]
can someone plz make a vid and show me how to get fortnite aimbot from this page

**Comment by kbdevs** [comment]
A video tutorial is coming sometime in the future,

Well first you'll need python
 https://www.python.org/downloads/ 
Install it and check the add to path option 
Run the script like I did in the bad tutorial
 if it says you dont have a module 
pip3 install (name of module) 
until it works
anymore issues past this https://chat.openai.com/
