### ISSUE TITLE
Issue with code and why cant i just use my mouse to aim?

### ISSUE THREAD

**Issue by RIFFMANJR** [kbdevs/ai-aimbot#20]
Hello KBDEVS, 

Just wanted to say love the work its a really interesting topic I'm not going to lie. 

My question / issue is that when it says what key do you want to hold to aim?

that's confusing as why do I need a key when ill be aiming with my mouse?

i don't really understand 

Thanks

![image](https://github.com/kbdevs/ai-aimbot/assets/145599045/02c11d18-754e-4c34-8f05-207285fb2463)

**Comment by kbdevs** [comment]
> Hello KBDEVS,
> 
> Just wanted to say love the work its a really interesting topic I'm not going to lie.
> 
> My question / issue is that when it says what key do you want to hold to aim?
> 
> that's confusing as why do I need a key when ill be aiming with my mouse?
> 
> i don't really understand
> 
> Thanks
> 
> ![image](https://user-images.githubusercontent.com/145599045/269369327-02c11d18-754e-4c34-8f05-207285fb2463.png)

They are issues with the current key press supporting mouth buttons.
As well it could be annoying if you didn't want to aim at that moment while holding it.

I'll look into ways that it could be supported.
