### ISSUE TITLE
Dont know how to run

### ISSUE THREAD

**Issue by Pyyrx0** [kbdevs/ai-aimbot#21]
As the title says,  the tut doesnt show us how to run, i made an issue alr but it didnt rly explain anything can you make a new tut

**Comment by kbdevs** [comment]
> As the title says, the tut doesnt show us how to run, i made an issue alr but it didnt rly explain anything can you make a new tut

What don't you understand about running?

In the tutorial it shows how to run in the terminal.

**Comment by Pyyrx0** [comment]
It really doesnt, it just cuts to it being run. can you please make a more in step tutorial?
