### ISSUE TITLE
How to use on valorant

### ISSUE THREAD

**Issue by Dogepoleon** [kbdevs/ai-aimbot#25]

**Comment by kbdevs** [comment]
A little more info needed, what exactly do you need help with?

**Comment by Dogepoleon** [comment]
how do i inject it?

**Comment by Seakza** [comment]
ye how do u use these for valorant like how do i open them and inject them

**Comment by kbdevs** [comment]
you guys can open a 1.3 version and follow all things on the readme and selecting valorant as the window

**Comment by Dogepoleon** [comment]
ok ty

**Comment by kbdevs** [comment]
> ok ty

did it work?

**Comment by Dogepoleon** [comment]
no

**Comment by kbdevs** [comment]
> no

More info
