### ISSUE TITLE
Fortnite Issue

### ISSUE THREAD

**Issue by exotikcheat** [kbdevs/ai-aimbot#26]
hello I tested on fortnite it doesn't work (I use window borderless) it only works when I'm out of the game..

**Comment by kbdevs** [comment]
> hello I tested on fortnite it doesn't work (I use window borderless) it only works when I'm out of the game..

What do you mean it only works while in windowed borderless, the detection? the aim?

**Comment by skullcheat** [comment]
my fortnite windows = windows borderless but not work
aim only work when i out of windows .

**Comment by kbdevs** [comment]
does it still shoot in game? or does aim and shoot not work in fn?
