### ISSUE TITLE
Apex

### ISSUE THREAD

**Issue by Surviv6669** [kbdevs/ai-aimbot#28]
When I use it on apex it shows a really zoomed in version. Can I make it not as zoomed in because if it detects a person and I shoot it doesn't detect long enough to snap all the way to the player.
![image](https://github.com/kbdevs/ai-aimbot/assets/146586795/9ca919cc-3244-48d1-91c9-802c8d146490)

**Comment by kbdevs** [comment]
> When I use it on apex it shows a really zoomed in version. Can I make it not as zoomed in because if it detects a person and I shoot it doesn't detect long enough to snap all the way to the player. ![image](https://user-images.githubusercontent.com/146586795/271791973-9ca919cc-3244-48d1-91c9-802c8d146490.png)

What resolution is your screen
Are you playing windowed fullscreen?

**Comment by Surviv6669** [comment]
i was playing windowed fullscreen and I believe I was using 2560x1600

**Comment by kbdevs** [comment]
> i was playing windowed fullscreen and I believe I was using 2560x1600. My actual screen is 2880x1800

I think you'll have to use the same res for both (screen, game) due to scaling, and if the detection then is in the right spot but a bit small ill fix that since its based on 1920

**Comment by Surviv6669** [comment]
I did the 3 options of 1920 and it still seems zoomed in. Also, what's the black square supposed to be?

**Comment by Surviv6669** [comment]
![image](https://github.com/kbdevs/ai-aimbot/assets/146586795/532fd087-6fc7-47f4-80e8-b34891e75798)
If I start program when apex is big and the resize it to really small its decent

**Comment by kbdevs** [comment]
> I did the 3 options of 1920 and it still seems zoomed in. Also, what's the black square supposed to be?

The black square blocks it from detecting the gun (idk its weird)

When everything was 1920 (Game & Display) was it detecting in the center?

**Comment by Surviv6669** [comment]
<img width="960" alt="image" src="https://github.com/kbdevs/ai-aimbot/assets/146586795/0ac9bea5-1a05-420b-a509-a4bf6745ca65">
This is what 1920x1200 looks like. So it's supposed to be for longer range fights? Darns.

**Comment by kbdevs** [comment]
> <img alt="image" width="960" src="https://user-images.githubusercontent.com/146586795/271889603-0ac9bea5-1a05-420b-a509-a4bf6745ca65.png"> This is what 1920x1200 looks like. So it's supposed to be for longer range fights? Darns.

something must be off since its looking at the wrong spot, are you sure that both the display in nvidia control panel and the game are set to 1920x1080?

**Comment by Surviv6669** [comment]
I opened nvidia control panel for the first time and I don't see any display resolution settings. But it was because of the automatic scaling my computer was doing. I must say it's not that accurate but I will live. Ty for help

**Comment by kbdevs** [comment]
> I opened nvidia control panel for the first time and I don't see any display resolution settings. But it was because of the automatic scaling my computer was doing. I must say it's not that accurate but I will live. Ty for help

1. How were you changing display res before?
Nvidia control panel -> Change resolution

2. So everything is working now?

**Comment by Surviv6669** [comment]
I used system settings lol
![image](https://github.com/kbdevs/ai-aimbot/assets/146586795/85b3338a-b257-402a-b0dd-f24dc93baa7b)

**Comment by kbdevs** [comment]
> I used system settings lol. Yes it works decently. If I took another 4 hours I could probably figure out how to make it use gpu tho. ![image](https://user-images.githubusercontent.com/146586795/272099116-85b3338a-b257-402a-b0dd-f24dc93baa7b.png)

Ah a laptop user its prob in some random utility, setting up opencv cuda is a pain
