### ISSUE TITLE
Hello, V1.2 streamer.py program cannot run. Can you help me check the problem? Thank you

### ISSUE THREAD

**Issue by lrlye** [kbdevs/ai-aimbot#3]
This is the code that reported an error：

[ WARN:0@72.348] global net_impl.cpp:178 cv::dnn::dnn4_v20230620::Net::Impl::setUpNet DNN module was not built with CUDA backend; switching to CPU

![微信截图_20230817130126](https://github.com/kbdevs/ai-aimbot/assets/93723706/a8976636-1462-4b73-bafe-5a20697edbad)
I think my cuda should be fine, right? thank you

**Comment by kbdevs** [comment]
does it still work on the cpu?

**Comment by lrlye** [comment]
> does it still work on the cpu?

yes，i'm Nvidia 2070 and i installed cuda

**Comment by kbdevs** [comment]
> > does it still work on the cpu?
> 
> yes，i'm Nvidia 2070 and i installed cuda

For it to use cuda you have to build opencv with cuda, guide at the bottom of the readme

**Comment by lrlye** [comment]
> > > does it still work on the cpu?
> > 
> > 
> > yes，i'm Nvidia 2070 and i installed cuda
> 
> For it to use cuda you have to build opencv with cuda, guide at the bottom of the readme

Okay, thank you. I'll give it a try
