### ISSUE TITLE
How exactly to use this?

### ISSUE THREAD

**Issue by 0x32-l3git** [kbdevs/ai-aimbot#30]
The instructions are very vague. It has a lot of issues.

**Comment by kbdevs** [comment]
> The instructions are very vague. It has a lot of issues.

Well what do you need help on, on the todo it says better tutorial.

**Comment by 0x32-l3git** [comment]
I mean like the keybind to aim, what does aim and shoot do? (does it shoot when aiming?)

**Comment by kbdevs** [comment]
> ean like the keybind to aim, what does aim and shoot do? (does it shoot when aiming?)

In the v1.3 versions it asks what keyboard key you want to hold to aim and shoot, the shoot option shoots and aims, the other just aims
