### ISSUE TITLE
User

### ISSUE THREAD

**Issue by XuHongFeii2** [kbdevs/ai-aimbot#31]
I have not tested whether Valorante can run this program normally. It is said in the introduction that it is invalid in Valorante. Will you update or fix this problem

**Comment by kbdevs** [comment]
> It is said in the introduction that it is invalid in Va
I assume you mean Valorant but in what introduction did it say anything about valorant being invalid?

**Comment by XuHongFeii2** [comment]
[NOTICES](https://github.com/kbdevs/ai-aimbot#notices)
The mouse movements are not functioning in VALORANT but it will still work as a triggerbot.

**Comment by kbdevs** [comment]
> [NOTICES](https://github.com/kbdevs/ai-aimbot#notices) The mouse movements are not functioning in VALORANT but it will still work as a triggerbot.

I currently have no plans to fix that as vanguard (valorant anticheat) is very invasive and would be quite hard to work around.
