### ISSUE TITLE
mouse event doesn't happen

### ISSUE THREAD

**Issue by leonardoReizz** [kbdevs/ai-aimbot#33]
https://github.com/kbdevs/ai-aimbot/blob/b75b6e3ccc611b2abbcf58729eec9d46e9da792e/V1.3%20Normal.py#L95}

The mouse event doesn't happen to me, I tested it in another code and it seems that this line doesn't do the aim assist, that is, it can't pull on the enemy

**Comment by kbdevs** [comment]
> [https://github.com/kbdevs/ai-aimbot/blob/b75b6e3ccc611b2abbcf58729eec9d46e9da792e/V1.3%20Normal.py#L95}](https://github.com/kbdevs/ai-aimbot/blob/b75b6e3ccc611b2abbcf58729eec9d46e9da792e/V1.3%20Normal.py#L95%7D)
> 
> The mouse event doesn't happen to me, I tested it in another code and it seems that this line doesn't do the aim assist, that is, it can't pull on the enemy

What game are you testing on?
