### ISSUE TITLE
Fortnite has alot of issues

### ISSUE THREAD

**Issue by dem2001** [kbdevs/ai-aimbot#36]
Firstly, the aimbot doesnt really affect the way you play fortnite (for me) because it only detects my player nothing else

**Comment by kbdevs** [comment]
You have to use the one of the detection blocker options so that it doesnt (v1.3)

**Comment by synxfr** [comment]
> You have to use the one of the detection blocker options so that it doesnt (v1.3)

Where is this in the script?
