### ISSUE TITLE
Crashes every single time

### ISSUE THREAD

**Issue by bkrisztina00** [kbdevs/ai-aimbot#37]
How to create an example issue request (copy paste and fill in) What's wrong:
Game: Fortnite
GPU: RTX 2070 S
CPU: i7 8700K
Windows Resolution: 1680x1050
Game Resolution: 1680x1050
OS: Windows 10
Any things you tried: Tried running with every single window setting:

C:\Users\Personal\Desktop\fortnite1>python3 "V1.3.Normal.py"
1: Command Prompt - python3  "V1.3.Normal.py"
2: Fortnite
3: Microsoft Text Input Application
4: NVIDIA GeForce Overlay
5: Program Manager
Enter the number of the window you want to select (0 to exit): 2
Selected window: Fortnite
Press 1 for shooting, or anything else for just aim:

After this I get a "Cropped Frame" which is grey, and after a few seconds it crashes.

**Comment by kbdevs** [comment]
What is the error being printed to console?
