### ISSUE TITLE
The script lagging

### ISSUE THREAD

**Issue by haramiste** [kbdevs/ai-aimbot#40]
Info:
Game: Fortnite
GPU: NVDIA GeForce GTX 1060 6GB
CPU: Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz (overclock 3.70GHz)
Windows Resolution: 1080 x 1920 @60hz
Game Resolution: 1080 x 1920 @165hz
OS: Windows 10 Professional (x64)

I thinks its my pc but if someone can opti the script would be great there is a video : 

https://streamable.com/z8lg3d

**Comment by kbdevs** [comment]
> Info: Game: Fortnite GPU: NVDIA GeForce GTX 1060 6GB CPU: Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz (overclock 3.70GHz) Windows Resolution: 1080 x 1920 @60Hz Game Resolution: 1080 x 1920 @165hz OS: Windows 10 Professional (x64)
> 
> I thinks its my pc but if someone can opti the script would be great there is a video :
> 
> https://streamable.com/z8lg3d

Yea unless you build with gpu/cuda it can be somewhat slow on cpu
