### ISSUE TITLE
The cheat is closed (VALORANT)

### ISSUE THREAD

**Issue by kamitanw21** [kbdevs/ai-aimbot#41]
Game: Valorant 
GPU: GeForce RTX 3070
CPU: Intel Core i5-10600F
Windows resolution: 1920x1080
Game resolution: 1920x1080 (window)
OS: Windows 10 Pro, Version 22H2

I installed opencv with cuda support using ChatGPT, I realized that I have OpenCV installed. However, when I try to select Valorant in V1.3 Normal, the program just closes. Before installing opencv with cuda, the cheat didn’t work for me, but at least it didn’t close.

I decided to open the cheat via CMD to send what error it gives me:

`Traceback (most recent call last): File "C:\Users\namva\OneDrive\Рабочий стол\ai-aimbot-main\V1.3 Normal.py", line 63, in <module> cv2.namedWindow('Cropped Frame', cv2.WINDOW_NORMAL) cv2.error: OpenCV(4.8.1) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window.cpp:1255: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvNamedWindow'`

update:

Well, now I’ve simply come to the conclusion that I can run a cheat. However, for some reason it still uses the CPU and not the GPU. And how cheat works? I dont understand, just check the video, also it doesn't aim 

https://youtu.be/YEQPsq1n-dI

This is what he tells me:
`[ WARN:0@6.766] global net_impl.cpp:178 cv::dnn::dnn4_v20230620::Net::Impl::setUpNet DNN module was not built with CUDA backend; switching to CPU`

**Comment by kbdevs** [comment]
> Game: Valorant GPU: GeForce RTX 3070 CPU: Intel Core i5-10600F Windows resolution: 1920x1080 Game resolution: 1920x1080 (window) OS: Windows 10 Pro, Version 22H2
> 
> I installed opencv with cuda support using ChatGPT, I realized that I have OpenCV installed. However, when I try to select Valorant in V1.3 Normal, the program just closes. Before installing opencv with cuda, the cheat didn’t work for me, but at least it didn’t close.
> 
> I decided to open the cheat via CMD to send what error it gives me:
> 
> `Traceback (most recent call last): File "C:\Users\namva\OneDrive\Рабочий стол\ai-aimbot-main\V1.3 Normal.py", line 63, in <module> cv2.namedWindow('Cropped Frame', cv2.WINDOW_NORMAL) cv2.error: OpenCV(4.8.1) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window.cpp:1255: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvNamedWindow'`
> 
> update:
> 
> Well, now I’ve simply come to the conclusion that I can run a cheat. However, for some reason it still uses the CPU and not the GPU. And how cheat works? I dont understand, just check the video, also it doesn't aim
> 
> https://youtu.be/YEQPsq1n-dI
> 
> This is what he tells me: `[ WARN:0@6.766] global net_impl.cpp:178 cv::dnn::dnn4_v20230620::Net::Impl::setUpNet DNN module was not built with CUDA backend; switching to CPU`

Seems you didn't fully build opencv with cuda and whatever you did do wasnt done correctly.
