### ISSUE TITLE
Not running

### ISSUE THREAD

**Issue by renner875** [kbdevs/ai-aimbot#42]
Hey so I have Python installed, I have run and downloaded the req.txt file, and I have also downloaded the project as a whole zip. However, when I double click V1.3 Normal, a screen pops up and then disappears immediately. What is wrong?

**Comment by kbdevs** [comment]
Run it through cmd to see what its saying.

Right click in the folder "Open In terminal"
Then python3 thescript.py

**Comment by renner875** [comment]
Hmm...
<img width="1079" alt="image" src="https://github.com/kbdevs/ai-aimbot/assets/123105246/1644de70-1e76-417f-a2b3-b1b096b99c8a">

It keeps on saying "Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.". I have checked the Execution Aliases and everything seems normal. You can also see that I checked to make sure I actually have Python. The error messages in red are from when I disabled the python3.exe files to see if anything would change(I did this in the Execution Aliases). I am not even sure I am entering the script correctly, although that doesn't seem to be the issue at the moment.

**Comment by kbdevs** [comment]
When installing python from the website make sure to check the add to path button
