### ISSUE TITLE
what do i download?

### ISSUE THREAD

**Issue by Dogepoleon** [kbdevs/ai-aimbot#45]
i ran the 1.3 regular and terminal popped up for a sec then went away, is there anything else i have to download/ do?

**Comment by kbdevs** [comment]
> ,

run it through terminal 
like python3 script.py
and say the error that it says

**Comment by Dogepoleon** [comment]
mb for late response but i downloaded all the libs and heres the error: net = cv2.dnn.readNetFromDarknet(CONFIG_FILE, WEIGHT_FILE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cv2.error: OpenCV(4.8.1) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\darknet\darknet_importer.cpp:210: error: (-212:Parsing error) Failed to open NetParameter file: ./yolov7-tiny.cfg in function 'cv::dnn::dnn4_v20230620::readNetFromDarknet'

**Comment by kbdevs** [comment]
Did you download the entire repository? It seems that you need the yolov7 config file from the repo to be in the same directory as the script you are running

**Comment by Dogepoleon** [comment]
yea I extracted it too idk what's happening

**Comment by kbdevs** [comment]
Unkown issue
