### ISSUE TITLE
Python screen comes up for a few seconds then closes itself

### ISSUE THREAD

**Issue by sdfdfsdd** [kbdevs/ai-aimbot#47]
This what comes up when I put it through terminal
https://github.com/kbdevs/ai-aimbot/assets/154296624/5f1667fa-82fd-48c2-bb8b-99d673696539

**Comment by sdfdfsdd** [comment]
the video is messed up the last few seconds shows the problem

**Comment by kbdevs** [comment]
You have the run it as a python script

python3 "script_name.py"

you can google or use chatgpt for more explanation

**Comment by sdfdfsdd** [comment]
Thank you but Ive run into another problem I have now installed what I believed to be the modules (req.txt) yet when I run "python3 V1.3Normal" it tells me that there is no module named numpy

**Comment by sdfdfsdd** [comment]
![Screenshot 2023-12-22 200652](https://github.com/kbdevs/ai-aimbot/assets/154296624/e80a8e2e-a5c7-43d9-9843-68fd6516d56f)

**Comment by kbdevs** [comment]
try pip3 install numpy

**Comment by sdfdfsdd** [comment]
it tells me the requirement is already satisfied

**Comment by kbdevs** [comment]
Could you send a screenshot? or paste in the console log

**Comment by sdfdfsdd** [comment]
![Uploading Screenshot 2023-12-25 185027.png…]()

**Comment by kbdevs** [comment]
you didnt wait for it to upload

**Comment by sdfdfsdd** [comment]
![Screenshot 2023-12-25 185027](https://github.com/kbdevs/ai-aimbot/assets/154296624/9eab79bc-f2ee-4b6c-b1e4-4aa384a45904)

**Comment by kbdevs** [comment]
is the fortnite window in windowed fullscreen?

**Comment by sdfdfsdd** [comment]
yes

**Comment by kbdevs** [comment]
What are all the options in the list of windows.

**Comment by xzripper** [comment]
```getWindowsWithTitle("Fortnite")```*

**Comment by kbdevs** [comment]
> `getWindowsWithTitle("Fortnite")`*

What are you trying to say here?

**Comment by xzripper** [comment]
It's code issue here, not user. There is no Fortnite variable defined.

**Comment by xzripper** [comment]
Try ```getWindowsWithTitle("Fortnite")``` instead of ```getWindowsWithTitle(Fortnite)```

**Comment by kbdevs** [comment]
It's not a code issue, the script works and detects windows, its on the users end

**Comment by sdfdfsdd** [comment]
> try pip3 install numpy

this is started to happen again and i have tried reinstalling numpy

**Comment by kbdevs** [comment]
make sure you are running and installing numpy on the same cmd window
