### ISSUE TITLE
Better Model and Faster Reading

### ISSUE THREAD

**Issue by MarshallMerz** [kbdevs/ai-aimbot#48]
Hey Man, you kind of inspired me to make an aimbot myself. I have a running version right now using YoloV8. It is gpu independent and runs at about 40 FPS. It also draws over the fortnite screen as opposed to in a CV2 window. If you want to collaborate I'd love to see what we could make. Right now I am trying to fine-tune my aiming function, which I see we both need to work on a bit.

**Comment by kbdevs** [comment]
I'd like to take a look, could you make a public repo on your profile?
