### ISSUE TITLE
Fortnite Bug

### ISSUE THREAD

**Issue by MooseMania45** [kbdevs/ai-aimbot#5]
When using the program in Fortnite, it automatically targets the user. Is there any way to solve this, or is it unfixable?

**Comment by kbdevs** [comment]
Hmm I didn't think about that, I'll have to add a block around the center for that. 

ETA: probably a few days

**Comment by william137m** [comment]
> Hmm I didn't think about that, I'll have to add a block around the center for that.
> 
> ETA: probably a few days

Was gonna post abt the same issue but I saw this post, Just wanted to lyk the aimbot works pretty good otherwise and I appreciate it!

**Comment by TOPDraling7485** [comment]
you can get help from https://t.me/+7HU4ehH2un0wZTVl

**Comment by kbdevs** [comment]
> > Hmm I didn't think about that, I'll have to add a block around the center for that.
> > ETA: probably a few days
> 
> Was gonna post abt the same issue but I saw this post, Just wanted to lyk the aimbot works pretty good otherwise and I appreciate it!

Just updated it, will be pushing updates
