### ISSUE TITLE
Fortnite 

### ISSUE THREAD

**Issue by Zeroxsho** [kbdevs/ai-aimbot#50]
aimbot detect my character

**Comment by kbdevs** [comment]
> aimbot detect my character

Use a 1.3 version and try the different block options

**Comment by Zeroxsho** [comment]
Need help how to do that?

**Comment by kbdevs** [comment]
In the console after running the script it will ask you where you want to put the block, the V1.3 version is in the repo

**Comment by Zeroxsho** [comment]
Hi,

That one where its says left or right?

**Comment by kbdevs** [comment]
Yea that is where it asks where you want the block
