### ISSUE TITLE
Hello, I have a question. Why do I need to draw a black rectangular box on the window

### ISSUE THREAD

**Issue by kkive** [kbdevs/ai-aimbot#51]
Hello man, I have a question. Why do I need to draw a black rectangular box on the window? What is the purpose of this black rectangular box
![image](https://github.com/kbdevs/ai-aimbot/assets/51246778/0ebfb5d1-59ab-4327-bca4-a9c041e6b0fd)

**Comment by kbdevs** [comment]
You can choose the none option but its used to block out some phantom detections on the gun or fortnite to block the character since it is thirdperson
