### ISSUE TITLE
valorant crosshair and popup issue

### ISSUE THREAD

**Issue by Alikhan911** [kbdevs/ai-aimbot#53]
even with the block, trying different resolutions for Valo, its either on the left or right corner of my screen, never on my crosshair, no matter what version I use or how much I try it doesn't change

**Comment by kbdevs** [comment]
Why would it be on your crosshair, its a block section.

**Comment by Alikhan911** [comment]
no its not where irs supposed ot be, the image grabber comes to either side of my corner depending on the block location, so the hack doesn't catch any people

**Comment by kbdevs** [comment]
Can you send a screenshot of the whole screen with this issue shown?

**Comment by abdulmannaan3108** [comment]
Hey bro sorry to come in between but can you guide me how to use this hack for valorant and are you banned yet?
