### ISSUE TITLE
window

### ISSUE THREAD

**Issue by waffles5793** [kbdevs/ai-aimbot#55]
Aimbot cropped frame window is laggy, and I dont know how to make it so it can see my entire screen to see enemies (it can see enemies, but it only captures like a fourth of the screen). Also, when do i input my keybind for turning the aimbot on and off? i cant find it anywhere

**Comment by kbdevs** [comment]
You hold the 1 key, (eventually will be changeable), the lag is just because it is using ai so it has to do the computation, the cropped frame goes around the crosshair so that it detects thing you actually want to shoot at.
