### ISSUE TITLE
Changeable Shoot Key (Getting Fixed)

### ISSUE THREAD

**Issue by kosogit** [kbdevs/ai-aimbot#56]
bro how to fire

**Comment by kbdevs** [comment]
Hold 1

**Comment by kosogit** [comment]
bro in fortnite 1 =1st gun

**Comment by kosogit** [comment]
it says press 1 for firing or just key for aim : 
I am entering key like "t" but still not firing

**Comment by kbdevs** [comment]
I've updated the language in the script for more understandability

"Press 1 for to enable shooting, or anything else for just aim to be enabled: \n"

**Comment by kbdevs** [comment]
Fixed, download AIMr V1.4

**Comment by kosogit** [comment]
it working but it aimbot is not working 
probably  because of detection do u need a video  on it

**Comment by kosogit** [comment]
while True:
    # ... (rest of the code)

    if shoot == "1":
        if keyboard.is_pressed('1'):  # Check if the "1" key is held
            # Shoot
            win32api.mouse_event(win32con.MOUSEEVENTF_LEFTDOWN, 0, 0, 0, 0)
            time.sleep(0.07)
            win32api.mouse_event(win32con.MOUSEEVENTF_LEFTUP, 0, 0, 0, 0)
    
    # ... (rest of the code)

**Comment by kbdevs** [comment]
Use the new version V1.4, also you have to hold down the key for it to aim
