### ISSUE TITLE
How do i run the file?

### ISSUE THREAD

**Issue by OPG-AOI** [kbdevs/ai-aimbot#6]

**Comment by OPG-AOI** [comment]
I keep getting this error: \\Downloads\\ai-aimbot-main\\V1.2 Normal': [Errno 2] No such file or directory

**Comment by OPG-AOI** [comment]
I keep getting this error: \Downloads\ai-aimbot-main\ai-aimbot-main\V1.2 Normal.py", line 1, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'

**Comment by bentoon00** [comment]
run pip install numpy in terminal

**Comment by OPG-AOI** [comment]
Requirement already satisfied: numpy in c:\users\my user\appdata\local\programs\python\python310\lib\site-packages (1.25.2)

**Comment by OPG-AOI** [comment]
how do i update it?

**Comment by RedDragX** [comment]
> how do i update it?

did u got any solution
