### ISSUE TITLE
https://www.virustotal.com/gui/file/0d1bb97f63756326bb8e7a4c5b071e8a753d0d0f470804b76ef20d6f80a6fd2b/detection

### ISSUE THREAD

**Issue by pompompur1nn** [kbdevs/ai-aimbot#61]
https://www.virustotal.com/gui/file/0d1bb97f63756326bb8e7a4c5b071e8a753d0d0f470804b76ef20d6f80a6fd2b/detection

**Comment by kbdevs** [comment]
WE KNOW, it has to download other files
