### ISSUE TITLE
[WARM:0@2.582] global net_impl.cpp:174 cv::dmn::dnn4_v20221220:Net::Impl::setUpNet DNN module was not built with CUDA backend;switching to CPU

### ISSUE THREAD

**Issue by a1434089782** [kbdevs/ai-aimbot#8]
[WARM:0@2.582] global net_impl.cpp:174 cv::dmn::dnn4_v20221220:Net::Impl::setUpNet DNN module was not built with CUDA backend;switching to CPU
How can i fix this?

**Comment by kbdevs** [comment]
I have a guide to build opencv with cuda at the bottom of the readme, it still works without cuda just considerably slower.

**Comment by YouCantCMe** [comment]
> I have a guide to build opencv with cuda at the bottom of the readme, it still works without cuda just considerably slower.

Danm I wish there was a way to install this easier. I tried for a couple of hours and could not get it working. Any other way you can get it to use gpu without all the hassle?
