### ISSUE TITLE
How do i start the normal.py file?

### ISSUE THREAD

**Issue by Xerox0987** [kbdevs/ai-aimbot#9]
As the title says How do i start the normal.py file?

**Comment by Xerox0987** [comment]
I downloaded python but now when i run it i get this error message:  File "C:\Users\jirir\Downloads\ai-aimbot-main\V1.3 Normal.py", line 1, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
PS C:\Users\jirir\Downloads\ai-aimbot-main>

**Comment by Amazingwowlol** [comment]
Run "pip install numpy".

Done.

**Comment by Xerox0987** [comment]
Traceback (most recent call last):
  File "C:\Users\jirir\Downloads\ai-aimbot-main\V1.2 Normal.py", line 2, in <module>
    import win32api, win32con, win32gui
ModuleNotFoundError: No module named 'win32api'
It says thaty i need to install win32api do you know how to?

**Comment by Xerox0987** [comment]
i fixed it by installing all of the dependencies thank you

**Comment by Xerox0987** [comment]
But now i get the error: 
  File "C:\Users\jirir\Downloads\ai-aimbot-main\V1.3 Normal.py", line 46, in <module>
    screen_info = gw.getWindowsWithTitle(Fortnite)[0]
                                         ^^^^^^^^
NameError: name 'Fortnite' is not defined
Do you know how to fix this?

**Comment by kbdevs** [comment]
> But now i get the error: File "C:\Users\jirir\Downloads\ai-aimbot-main\V1.3 Normal.py", line 46, in screen_info = gw.getWindowsWithTitle(Fortnite)[0] ^^^^^^^^ NameError: name 'Fortnite' is not defined Do you know how to fix this?

Use the newer V1.3 files, as it has a better window selector.
